<?php

$title = 'Delete Book';
$this->headTitle($title);
?>

<h1>Delete a book</h1>

<p>Are you sure you want to delete <?php echo $this->escapeHtml($book->title); ?>?</p>

<?php
$url = $this->url('book', [
    'action' => 'delete',
    'id' => $this->id,
]);
?>

<form action="<?php echo $url; ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo (int) $book->id; ?>">
        <input type="submit" name="del" value="Yes">
        <input type="submit" name="del" value="No">
    </div>
</form>
